# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12dcc890039a9df940211d0e9f86093d8291f75b1507fa354f990899b09a903f7f48e836b8ec1b659d6c7b61d668c114d28cce0dce0fb7e62b1f89a36c2f0fbd

test:
  secret_key_base: 3dccc196be06aa182df09c07998d7a3f13859b2bc33522e0991bbeacb9497b10b9f78df7ab43b89573c308d038df48e5edbaba88366299635035b950285287ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
