# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d2c81f2822acb3c770d2c3045323f8faf2b723ec8658e52a919b1101e3fd1d64d5f084a061c872e6aa9bdf572016a923620baf835cafe8dacd88e99c7ad1e4

test:
  secret_key_base: bd0b6920c449ba1baa3d68c242081d7be53e42605d262fea38a35bd6dc8d5b83e21d7670f54ce924e4bfcc22968a5b24ec19ea1da86bea1ffceda32e9254926b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
